
envvar:
    fit_suffix: v1

fit_start: 2002-06-01
fit_end: 2018-01-01

output_file: fit_version1.csv


ndo_file: ndo.csv
mrz_elev_file: mrz.csv

storage_area: 34925.0

so : 32000
sb: 200.
storage_aread: 35923.48
filter_setup:
    dt: 3h
    k0: -6
    filter_length: 13     # 3h, -0 and 13 were well conditioned
    centering: causal   # must be 'centered' or 'causal'

param:
    log10gbeta: [9.5,8.0,12.]
    npow: [1.0,0.6,1.5]
    b0: [0., -0.25,0.25]
    b1: [1., -0.25,0.25]
    afilt: [[1.59e-4, -1.28e-5, 6.96e-6, 4.83e-5, -7.67e-5, 6.93e-5, -3.85e-5],
            [-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5],
            [0.5,0.5,0.5,0.5,0.5,0.5,0.5]
            ]
