name: env_mrzecest
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.11
  - pip>=22.2
  - dms-datastore>=0.0.16
  - ipykernel
  - jupyter_bokeh
  - vtools3>=3.7.5
  - bokeh>=2.4
  - pandas>=2 
  - numpy>=1.21.6
  - matplotlib
  - dask>=2022.11
  - numba>=0.56
  - pyhecdss
  # dev dependencies
  - pytest
  - pytest-cov
  - black

  # setup development environment by 
  # conda activate env_mrzecest
  # pip install --no-deps -e .

